### ISSUE TITLE
Referencing frames

### ISSUE THREAD

**Issue by jeroenrottink** [jdredd87/iwFrameTemplateJavaScriptAjaxDemo#1]
In the current version the frames are referenced eg {%frame1IWRegionFrame1%}. In IW15.1.22 this doesn't include the frames and results in JavaScript errors.
If you change it into {%frame1.IWRegionFrame1%} it works.

Nice example btw.

**Comment by jdredd87** [comment]
Thanks, Ill update it and mention how demo is now for at least IW15.1.17+ since they changed how frames / templates work.
